server:
   port: 8083

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
         
jwt:
   token:
     secret: U29nZXRpIGlzIGVlbiBoZWVsIGVyZyBnYWFmIGJlZHJpamYhIA==

management:
   endpoints:
      web:
         exposure:
            include: '*'
   tracing:
      enabled: true
      sampling:
         probability: 1.0
      propagation:
         type: b3
      zipkin:
         tracing: endpoint= localhost:9411/zipkin/api/v2/spans

spring:
   datasource:
      url: jdbc:mysql://localhost:3306/user_db?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&charSet=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: spring
      password: jpa!
      max-poolsize: 20
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
         ddl-auto: validate
      show-sql: false

customer_db:
   datasource:
      properties:
         hibernate.dialect: org.hibernate.dialect.MySQLDialect
         hibernate.show_sql: false
         hibernate.id.new_generator_mappings: false
         
springdoc:
  api-docs:
    enabled: true 
    path: /user/v3/api-docs
  swagger-ui:
    enabled: true
    path: /user/swagger-ui.html
         
openApi:
    apiName: Authentication Service API
    serverUrl: http://localhost:8083