server:
   port: 8081

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/

management:
   tracing:
      enabled: true
      sampling:
         probability: 1.0
      propagation:
         type: b3
      zipkin:
         tracing: endpoint= localhost:9411/zipkin/api/v2/spans